baseURL = "https://joeyinnes.com"
languageCode = "en-us"
title = "Joey Innes"
pluralizelisttitles = false
paginate = 12

[security]
  [security.funcs]
    getenv = [
      "^HUGO_",
      "^CI$",
      "HIDDEN_SERVICE_HOSTNAME",
      "COMMIT_HASH",
      "CF_PAGES_COMMIT_SHA"
    ]

[params]
  author = "Joey Innes"
  description = "A record of reflections, going fast, and musings over our bitcoin, AI and other tech."

  [params.categories]
    cs = "Computer Broscience"
    reflections = "Reflections"
    going-fast = "Going Fast"

[permalinks]
  categories = "/:slug/"

[menu]
  [[menu.main]]
    name = "Computer Broscience"
    url = "/cs"
    weight = 1
  [[menu.main]]
    name = "Going Fast"
    url = "/going-fast"
    weight = 2
  [[menu.main]]
    name = "Reflections"
    url = "/reflections"
    weight = 3
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/intob"
    weight = 4
  [[menu.main]]
    name = "YouTube"
    url = "https://youtube.com/@joeyinnes"
    weight = 5
  [[menu.main]]
    name = "Telegram"
    url = "https://telegram.me/joeyinnes"
    weight = 6
  [[menu.main]]
    name = "Nostr"
    url = "/npub.txt"
    weight = 7
  [[menu.main]]
    name = "PGP"
    url = "/pgp.txt"
    weight = 8
